dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - git

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.9.0/bazel_0.9.0-linux-x86_64.deb
  - wget https://github.com/bazelbuild/bazel/releases/download/0.9.0/bazel_0.9.0-linux-x86_64.deb.sha256
  - sha256sum -c bazel_0.9.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.9.0-linux-x86_64.deb
  - cd .. && git clone https://github.com/JonNRb/bazel_asm

script:
  - bazel build //...
